// <auto-generated />
namespace CourseBooking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class base21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(base21));
        
        string IMigrationMetadata.Id
        {
            get { return "201507111006482_base21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
